//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: AssemblyVersion("1.13.3")]
[assembly: AssemblyFileVersion("1.13.3")]

// Generated by the MSBuild WriteCodeFragment class on 23/04/2014 15:15:37.

